---
- name: start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: install epel-release
  yum:
    name: epel-release
    state: installed

# GitBucket requires MySQL >= 5.7
- name: install mysql repo
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    state: installed
    validate_certs: yes

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: epel
  with_items:
    - java-1.8.0-openjdk
    - nginx
    - mysql-community-server
    # ansible module requirements
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: check whether mysql is initialized
  stat:
    path: /var/lib/mysql
  register: is_mysql_inited

- name: initialize mysql without password
  command: mysqld --initialize-insecure
  when: not is_mysql_inited.stat.exists

- name: "modify mysql files' permission"
  file:
    path: /var/lib/mysql
    recurse: yes
    owner: mysql
    group: mysql

- name: run and enable mysql
  systemd:
    name: mysqld
    enabled: yes
    state: started

- name: change mysql root password
  mysql_user:
    check_implicit_admin: yes
    name: root
    password: "{{ mysql_root_password }}"
  when: not is_mysql_inited.stat.exists

- name: create database
  mysql_db:
    name: gitbucket
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: present
    encoding: utf8
  when: not is_mysql_inited.stat.exists

- name: create mysql user
  mysql_user:
    name: gitbucket
    password: "{{ mysql_password }}"
    priv: gitbucket.*:ALL
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: not is_mysql_inited.stat.exists

- name: put gitbucket.war
  get_url:
    url: https://github.com/gitbucket/gitbucket/releases/download/4.18.0/gitbucket.war
    dest: /gitbucket.war
    checksum: sha256:471e33b67567b8c53faac88b3d148de73ad4d96452cbb5ad4983ee3e975e19dd

- name: put systemd service file
  copy:
    src: files/gitbucket.service
    dest: /etc/systemd/system/gitbucket.service

- name: put nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: put nginx proxy.conf
  copy:
    src: files/proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf

- name: open firewall(HTTP)
  firewalld:
    permanent: yes
    service: http
    state: enabled
    immediate: yes

- name: configure selinux for http reverse proxy
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: run and enable gitbucket
  systemd:
    name: gitbucket
    daemon_reload: yes
    enabled: yes
    state: started

- name: put database config
  template:
    src: templates/database.conf.j2
    dest: /root/.gitbucket/database.conf

- name: restrat gitbucket
  systemd:
    name: gitbucket
    state: restarted

- name: start and enable nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
